### ISSUE TITLE
Can not use docker compose for sample prometheus-grafana

### ISSUE THREAD

**Issue by ssabat** [docker/awesome-compose#134]
I wanted to run Prometheus Grafana docker compose sample. I see following error message.

d:\awesome-compose\prometheus-grafana>docker-compose up -d
Creating prometheus ... error
Creating grafana    ...

ERROR: for prometheus  Cannot create container for service prometheus: status code not OK but 500:  ☺   ˙˙˙˙☺       ♀☻   FDocker.Core, Version=3.0.2.51106, Culture=neutral, PublicKeyToken=null♣☺   ←Docker.Core.DockerException♀      ClassNameMessage♦Data♫InnerExceptionHelpURL►StackTraceString▬RemoteStackTraceString►RemoteStackIndex☼ExceptionMethodHResult♠SourWatsonBuckets☺☺♥♥☺☺☺ ☺ ☺▲System.Collections.IDictionary►System.Excepti☻☻   ♠♥   ←Docker.Core.DockerException♠♦   ▲Filesharing has been cancelled

♠♣   Ś‼   at Docker.ApiServices.Mounting.FileSharing.<DoShareAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\Mounting\FileSharing.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by glours** [comment]
Can you check that the port `9090` isn't already used?

**Comment by mikesir87** [comment]
Closing this issue due to inactivity. If you have any future needs, please feel free to open a new issue. Thanks!
