### ISSUE TITLE
nginx-flask-mysql/backend-requirements.txt file needs to update

### ISSUE THREAD

**Issue by dazimax** [docker/awesome-compose#223]
nginx-flask-mysql requirements.txt file needs to be updated with the below

```
Flask==2.0.1
itsdangerous==2.0.1
mysql-connector==2.2.9
```

Otherwise it will give the below error

```
backend_1  | Traceback (most recent call last):
backend_1  |   File "/usr/local/bin/flask", line 5, in <module>
backend_1  |     from flask.cli import main
backend_1  |   File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
backend_1  |     from . import json
backend_1  |   File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 15, in <module>
backend_1  |     from itsdangerous import json as _json
backend_1  | ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)
```

**Comment by stewartmbofana** [comment]
@dazimax can you create a Pull Request for it. Thanks
